#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
print(np.show_config())

2.3.5
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/HP/anaconda3/Library/include
    lib directory: C:/Users/HP/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/HP/anaconda3/Library/include
    lib directory: C:/Users/HP/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.1

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
arr=np.zeros(10, dtype=float)     # zeros array is a null vector
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
print(arr.nbytes)
print(arr.size * arr.itemsize)
print(arr.itemsize)

80
80
8


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
a=np.arange(10,49)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
a[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
arr=np.array([1,2,0,0,4,0])
np.nonzero(arr)[0]

array([0, 1, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
np.random.rand(3,3,3)

array([[[0.48657116, 0.29146718, 0.28365894],
        [0.03024886, 0.109306  , 0.30587977],
        [0.01266041, 0.99011255, 0.42740381]],

       [[0.03741061, 0.92756306, 0.66170812],
        [0.10964667, 0.84113444, 0.5427968 ],
        [0.92358068, 0.319281  , 0.23089504]],

       [[0.36209908, 0.2487827 , 0.94727484],
        [0.74925239, 0.52641612, 0.94097655],
        [0.94454926, 0.64399365, 0.26079811]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
a=np.random.rand(10,10)
print(a)
print(a.max())
print(a.min())

[[0.75590698 0.66479283 0.36109429 0.46525259 0.89011279 0.15364557
  0.17146794 0.36150658 0.95027573 0.3399732 ]
 [0.9468621  0.67963333 0.91419598 0.98010377 0.6013112  0.45471771
  0.36080704 0.43351037 0.54485987 0.34394626]
 [0.06173029 0.41578799 0.98870126 0.18878423 0.2235133  0.53855543
  0.33211126 0.50686804 0.66072307 0.36380848]
 [0.35363179 0.50598375 0.48829453 0.4494211  0.48583159 0.84846399
  0.64212896 0.50016548 0.82877863 0.72539115]
 [0.13869418 0.32715835 0.49399243 0.33394048 0.17164096 0.80618335
  0.79458643 0.53727003 0.1186228  0.5814031 ]
 [0.47237019 0.25312922 0.74405789 0.22301178 0.14129868 0.76179467
  0.52370714 0.04442596 0.80686184 0.24515349]
 [0.72857909 0.0820673  0.06285712 0.62492136 0.0242636  0.56945279
  0.66965908 0.58040089 0.44420463 0.83337342]
 [0.25222718 0.46501628 0.68165768 0.51521124 0.30165292 0.92101158
  0.06321668 0.80108428 0.78708417 0.16828913]
 [0.3554207  0.97794219 0.98691516 0.79470134 0.88808629 0.12639853
  0.14659171

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
a=np.arange(1,31).reshape(2,3,5)
print(a.mean())

15.5


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
a=np.zeros((5,5))
a[-1:]=1
a[:1]=1
a[:,0]=1
a[:,-1]=1
a



array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
a=np.ones((3,3))
np.pad(a, pad_width=1, mode='constant',constant_values=0)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan-np.nan)
print(np.nan in set ([np.nan]))
print(0.3==3*0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
a=np.zeros((5,5), dtype=int)
a
value=np.array([1,2,3,4])
np.fill_diagonal(a[1:],value)


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
a=np.zeros((8,8) ,dtype=int)
a[::2,::2]=1
a[1::2,1::2]=1
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [21]:
a=np.random.randn(6,7,8)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
a=np.array([[0,1],[1,0]])
np.tile(a, (4,4))


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
a=np.random.randn(5,5)
a//1


array([[-2., -1., -1., -1., -1.],
       [-1.,  0.,  0., -1.,  0.],
       [-1., -2.,  1., -1.,  0.],
       [ 0.,  0., -1.,  1.,  0.],
       [-1., -1., -3.,  0., -1.]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
a=np.full((5,3),5)
b= np.arange(1,13,2).reshape(3,2)
np.matmul(a,b)

array([[ 75, 105],
       [ 75, 105],
       [ 75, 105],
       [ 75, 105],
       [ 75, 105]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
a=np.arange(1,12)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9


10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [27]:
z=np.arange(1,5)
print(z)
print(z**z)
print(2<< z >> 2)
print(z <- z)
print(1j*z)
print(z/1/1)
z=z.any()
print(z<z>z)


[1 2 3 4]
[  1   4  27 256]
[1 2 4 8]
[False False False False]
[0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[1. 2. 3. 4.]
False


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [28]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
np.array([np.nan]).astype(int).astype(float)

nan
0


C:\Users\HP\AppData\Local\Temp\ipykernel_27360\3474556150.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\HP\AppData\Local\Temp\ipykernel_27360\3474556150.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\HP\AppData\Local\Temp\ipykernel_27360\3474556150.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [29]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### 30. How to find common values between two arrays? (★☆☆)

In [30]:
a=np.arange(1,20)
b=np.arange(8,25,2)
np.intersect1d(a,b)

array([ 8, 10, 12, 14, 16, 18])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [31]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\HP\AppData\Local\Temp\ipykernel_27360\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [32]:
today=np.datetime64('today','D')
tommorow=today+np.timedelta64(1,'D')
yesterday=today-np.timedelta64(1,'D')
print(today)
print(yesterday)
print(tommorow)

2026-03-10
2026-03-09
2026-03-11


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [33]:
dates=np.arange('2016-07-01','2016-08-01', dtype='datetime64[D]')
print(dates)
len(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


31

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [34]:
a=np.array([1,2,3,4])
b=np.array([2,4,2,4])
(a+b)*(-a/2)

array([ -1.5,  -6. ,  -7.5, -16. ])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [35]:
a=np.random.rand(3,3)
a.astype(int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [36]:
np.linspace(0,4,25).reshape(5,5)

array([[0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667],
       [0.83333333, 1.        , 1.16666667, 1.33333333, 1.5       ],
       [1.66666667, 1.83333333, 2.        , 2.16666667, 2.33333333],
       [2.5       , 2.66666667, 2.83333333, 3.        , 3.16666667],
       [3.33333333, 3.5       , 3.66666667, 3.83333333, 4.        ]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [37]:
np.linspace(0.1,0.99999999,10)

array([0.1       , 0.2       , 0.3       , 0.4       , 0.5       ,
       0.59999999, 0.69999999, 0.79999999, 0.89999999, 0.99999999])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [50]:
a=np.random.randint(1,100,size=10)
a.sort()
a

array([ 2,  7,  9, 18, 21, 48, 59, 62, 82, 94], dtype=int32)

In [39]:
%%time
arr=np.array([1,2,3,4])
arr.sum()

CPU times: total: 0 ns
Wall time: 153 μs


np.int64(10)

In [40]:
%%time
np.sum(arr)

CPU times: total: 0 ns
Wall time: 61.8 μs


np.int64(10)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [44]:
a=np.array([1,2,3,4,5])
b=np.array([1,3,4,5,6])
np.equal(a,b).all()

np.False_

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [65]:
a=np.random.randint(1,100,size=10)
print(a)
print(a.max())
a[a.argmax()]=0
print(a)

[76 83 81 80 80 69 76 63 80 50]
83
[76  0 81 80 80 69 76 63 80 50]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [73]:
a=np.full((3,2,2),42)
a.view()

array([[[42, 42],
        [42, 42]],

       [[42, 42],
        [42, 42]],

       [[42, 42],
        [42, 42]]])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [80]:
arr=np.array([[1,2,3,4],
              [5,6,7,8],
              [1,2,3,4],
              [9,8,7,0]])
np.unique_inverse(arr)

UniqueInverseResult(values=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), inverse_indices=array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [9, 8, 7, 0]]))

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)